; --- SMARTGREENHOUSE FAN PROJECT CONFIGURATION ---
; 
; COMMANDS TO COMPILE & UPLOAD (Standard):
;   1. Hardware   : pio run -e hardware -t upload
;   2. Simulation : pio run -e simulation
;
; COMMANDS TO COMPILE & UPLOAD (MAC / LINUX - Full Path):
;   1. Hardware   : ~/.platformio/penv/bin/pio run -e hardware -t upload
;   2. Simulation : ~/.platformio/penv/bin/pio run -e simulation
;
; COMMANDS TO COMPILE & UPLOAD (WINDOWS POWERSHELL - Full Path):
;   1. Hardware   : & "$env:USERPROFILE\.platformio\penv\Scripts\pio" run -e hardware -t upload
;   2. Simulation : & "$env:USERPROFILE\.platformio\penv\Scripts\pio" run -e simulation
;
; MONITOR COMMAND:
;   Standard   : pio device monitor -b 115200
; ----------------------------------------------

[platformio]
default_envs = hardware

[env:hardware]
platform = espressif32
board = esp32dev
framework = arduino
build_src_filter = +<main.cpp>
lib_deps =
  adafruit/DHT sensor library
  adafruit/Adafruit Unified Sensor
  marcoschwartz/LiquidCrystal_I2C
  tzapu/WiFiManager
  blynkkk/Blynk @ ^1.3.2
monitor_speed = 115200

[env:simulation]
platform = espressif32
board = esp32dev
framework = arduino
build_src_filter = +<main_sim.cpp>
lib_deps =
  adafruit/DHT sensor library
  adafruit/Adafruit Unified Sensor
  marcoschwartz/LiquidCrystal_I2C
  blynkkk/Blynk @ ^1.3.2
monitor_speed = 115200
